[package]
name = "raycaster"
version = "0.1.0"
authors = ["Nishant Mahajan <nishant.mahajanXVII@gmail.com>"]
edition = "2018"

[dependencies]
auto_ops = "0.1.0"
env_logger = "0.8.2"
log = "0.4.11"
pixels = "0.2.0"
png = "0.16.8"
thiserror = "1.0.23"
winit = "0.24.0"
winit_input_helper = "0.9.0"
