[package]
name = "raycaster"
version = "0.1.0"
authors = ["Nishant Mahajan <nishant.mahajanXVII@gmail.com>"]
edition = "2018"

[dependencies]
auto_ops = "0.1.0"
pixels = "0.2.0"
png = "0.16.8"
winit = "0.24.0"
winit_input_helper = "0.9.0"
